### ISSUE TITLE
这个乱码你知道怎么解决吗 谢谢了

### ISSUE THREAD

**Issue by Kotodian** [shanghai-edu/ldap-test-tool#3]
![image](https://user-images.githubusercontent.com/22030659/89708341-e486e400-d9a8-11ea-9986-362a2708ca73.png)
![image](https://user-images.githubusercontent.com/22030659/89708351-fbc5d180-d9a8-11ea-9eb6-e8fba80288c0.png)

**Comment by freedomkk-qfeng** [comment]
这应该是 ldap 里存的编码格式和你操作系统不一致吧。
得先搞清楚是个什么编码
