### ISSUE TITLE
添加 go module 支持

### ISSUE THREAD

**Issue by TieWay59** [shanghai-edu/ldap-test-tool#4]
本项目开发时间早在 go module 诞生之前，当时没有官方的包依赖管理方案。经过与维护者 @freedomkk-qfeng  讨论，我们准备帮助本项目添加 go module 支持。

潜在的困难：

- 老版本冲突
- 编译测试出现意外

后续遇到相关的小问题，我会根据进一步的实验聚合到本 issue。

**Comment by freedomkk-qfeng** [comment]
因为要兼容原来的包引入，实际上只能有 github.com/shanghai-edu/ldap-test-tool 这一种方式
